---
- hosts: db
  become: yes
  gather_facts: no
  roles:
    - common
  tasks:
    - name: ensure packages are installed
      apt:
        name:
          - postgresql
          - libpq-dev
          - python3-psycopg2

- hosts: db
  become: yes
  become_user: postgres
  gather_facts: no
  vars:
    database: ads_microservice_production
    database_auth: auth_microservice_production
    user: ads
    password: UNIq4rrqWXzJ5H0t
  tasks:
    - name: ensure database is created
      postgresql_db:
        name: '{{ database }}'
    - name: ensure database auth is created
      postgresql_db:
        name: '{{ database_auth }}'

    - name: ensure user has access to database
      postgresql_user:
        db: '{{ database }}'
        name: '{{ user }}'
        password: '{{ password }}'
        priv: ALL

    - name: ensure user has access to auth database
      postgresql_user:
        db: '{{ database_auth }}'
        name: '{{ user }}'
        password: '{{ password }}'
        priv: ALL

    - name: ensure user has no extra privileges
      postgresql_user:
        name: '{{ user }}'
        role_attr_flags: NOSUPERUSER,NOCREATEDB

    - name: ensure no other user can access
      postgresql_privs:
        db: '{{ database }}'
        role: PUBLIC
        type: database
        priv: ALL
        state: absent

    - name: ensure no other user can access
      postgresql_privs:
        db: '{{ database_auth }}'
        role: PUBLIC
        type: database
        priv: ALL
        state: absent
