---
- hosts: rabbitmq
  become: yes
  gather_facts: no
  tasks:
    - name: Run expect to wait for a successful PXE boot via out-of-band CIMC
      shell: |
        apt-get install curl gnupg debian-keyring debian-archive-keyring apt-transport-https -y
        apt-key adv --keyserver "hkps://keys.openpgp.org" --recv-keys "0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"
        curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key | apt-key add -
        curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key | apt-key add -
        tee /etc/apt/sources.list.d/rabbitmq.list <<EOF
        deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu bionic main
        deb-src https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu bionic main
        deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu bionic main
        deb-src https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu bionic main
        EOF
        apt-get update -y
        apt-get install -y erlang-base \
                                erlang-asn1 erlang-crypto erlang-eldap erlang-ftp erlang-inets \
                                erlang-mnesia erlang-os-mon erlang-parsetools erlang-public-key \
                                erlang-runtime-tools erlang-snmp erlang-ssl \
                                erlang-syntax-tools erlang-tftp erlang-tools erlang-xmerl
        apt-get install rabbitmq-server -y --fix-missing
    - name: ensure rabbitmq plugins are installed
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - restart rabbitmq
  handlers:
    - name: restart rabbitmq
      service:
        name: rabbitmq-server
        state: restarted

- hosts: rabbitmq
  become: yes
  gather_facts: no
  vars:
    user: ads
    password: UNIq4rrqWXzJ5H0t
  tasks:
    - name: ensure rabbitmq user is present
      rabbitmq_user:
        user: '{{ user }}'
        password: '{{ password }}'
        tags: administrator
        vhost: /
        configure_priv: .*
        write_priv: .*
        read_priv: .*
        state: present
    - name: ensure guest user is absent
      rabbitmq_user:
        user: guest
        state: absent
